"""Protocol interfaces for storage backends."""

from __future__ import annotations

from typing import Protocol

from wisdom.models.experience import Experience
from wisdom.models.knowledge import Knowledge
from wisdom.models.wisdom import Wisdom
from wisdom.models.common import Relationship


class ExperienceStore(Protocol):
    def save_experience(self, exp: Experience) -> None: ...
    def get_experience(self, id: str) -> Experience | None: ...
    def list_experiences(self, domain: str | None = None, limit: int = 100, offset: int = 0) -> list[Experience]: ...
    def delete_experience(self, id: str) -> bool: ...
    def count_experiences(self, domain: str | None = None, unprocessed: bool = False) -> int: ...
    def mark_processed(self, ids: list[str]) -> None: ...
    def get_unprocessed(self, domain: str | None = None, limit: int = 50) -> list[Experience]: ...


class KnowledgeStore(Protocol):
    def save_knowledge(self, k: Knowledge) -> None: ...
    def get_knowledge(self, id: str) -> Knowledge | None: ...
    def list_knowledge(self, domain: str | None = None, limit: int = 100, offset: int = 0) -> list[Knowledge]: ...
    def delete_knowledge(self, id: str) -> bool: ...
    def count_knowledge(self, domain: str | None = None, unsynthesized: bool = False) -> int: ...
    def mark_synthesized(self, ids: list[str]) -> None: ...
    def get_unsynthesized(self, domain: str | None = None, limit: int = 50) -> list[Knowledge]: ...


class WisdomStore(Protocol):
    def save_wisdom(self, w: Wisdom) -> None: ...
    def get_wisdom(self, id: str) -> Wisdom | None: ...
    def list_wisdom(self, domain: str | None = None, lifecycle: str | None = None, limit: int = 100, offset: int = 0) -> list[Wisdom]: ...
    def delete_wisdom(self, id: str) -> bool: ...
    def count_wisdom(self, domain: str | None = None) -> int: ...
    def update_wisdom(self, w: Wisdom) -> None: ...


class RelationshipStore(Protocol):
    def save_relationship(self, r: Relationship) -> None: ...
    def get_relationships(self, entity_id: str, entity_type: str | None = None) -> list[Relationship]: ...
    def find_conflicts(self, entity_id: str) -> list[Relationship]: ...
    def delete_relationship(self, id: str) -> bool: ...
